
import java.awt.event.ActionEvent;
import java.io.File;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.SwingWorker;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jonathan
 */
public class Gui extends javax.swing.JFrame {

    /**
     * Creates new form Gui
     */
    public Gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        httplabel = new javax.swing.JLabel();
        blogname = new javax.swing.JTextField();
        tumblrlabel = new javax.swing.JLabel();
        start = new javax.swing.JTextField();
        tolabel = new javax.swing.JLabel();
        end = new javax.swing.JTextField();
        runbutton = new javax.swing.JButton();
        resetbutton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        thumbbar = new javax.swing.JToolBar();
        hiresbutton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        image = new javax.swing.JLabel();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        httplabel.setText("http://");

        blogname.setColumns(10);

        tumblrlabel.setText(".tumblr.com/page");

        start.setColumns(3);

        tolabel.setText("to");

        end.setColumns(3);

        runbutton.setText("Run");
        runbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runbuttonActionPerformed(evt);
            }
        });

        resetbutton.setText("Reset");
        resetbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbuttonActionPerformed(evt);
            }
        });

        thumbbar.setFloatable(false);
        thumbbar.setRollover(true);
        jScrollPane1.setViewportView(thumbbar);

        hiresbutton.setText("Hi-Res");
        hiresbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hiresbuttonActionPerformed(evt);
            }
        });

        image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jScrollPane2.setViewportView(image);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(httplabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(blogname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tumblrlabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tolabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(end, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(runbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hiresbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resetbutton)
                        .addGap(0, 64, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(httplabel)
                    .addComponent(blogname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tumblrlabel)
                    .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tolabel)
                    .addComponent(end, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(runbutton)
                    .addComponent(resetbutton)
                    .addComponent(hiresbutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void runbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runbuttonActionPerformed
        Main.blogname = this.blogname.getText();
        Main.load();        
        Main.run(Integer.parseInt(this.start.getText()), Integer.parseInt(this.end.getText()));
        thumbbar.removeAll();
        loadimages.execute();
        Main.save();
        hiresbutton.setEnabled(true);
    }//GEN-LAST:event_runbuttonActionPerformed

    private void resetbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbuttonActionPerformed
        Main.blogname = this.blogname.getText();
        Main.reset();
        hiresbutton.setEnabled(false);
    }//GEN-LAST:event_resetbuttonActionPerformed

    private void hiresbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hiresbuttonActionPerformed
        Main.downloadHiRes();
        Main.save();
    }//GEN-LAST:event_hiresbuttonActionPerformed

        private MissingIcon placeholderIcon = new MissingIcon();
    
    private SwingWorker<Void, ThumbnailAction> loadimages = new SwingWorker<Void, ThumbnailAction>() {
        @Override
        protected Void doInBackground() throws Exception {
            for(Picture picture: Main.pic_pic_hash.keySet()){
                ImageIcon icon;
                String location = Main.blogname+File.separator+picture.md5_id+File.separator+picture.lo_name;
                String url = picture.lo_url;
                if(picture.downloaded_orig){
                    location = Main.blogname+File.separator+picture.md5_id+File.separator+picture.hi_name;
                    url = picture.hi_url;
                }            
                icon = new ImageIcon(location, url);
                ThumbnailAction thumbAction;
                if(icon != null){                    
                    ImageIcon thumbnailIcon = new ImageIcon(Main.blogname+File.separator+picture.md5_id+File.separator+"thumbnail.jpg");                    
                    thumbAction = new ThumbnailAction(icon, thumbnailIcon, url);                    
                }else{
                    thumbAction = new ThumbnailAction(placeholderIcon, placeholderIcon, url);
                }
                publish(thumbAction);
            }
            return null;
        }
        @Override
        protected void process(List<ThumbnailAction> chunks) {
            for (ThumbnailAction thumbAction : chunks) {
                JButton thumbButton = new JButton(thumbAction);
                thumbbar.add(thumbButton, thumbbar.getComponentCount() - 1);
            }
        }
    };

    private class ThumbnailAction extends AbstractAction{
        private Icon displayPhoto;
        public ThumbnailAction(Icon photo, Icon thumb, String desc){
            displayPhoto = photo;
            putValue(SHORT_DESCRIPTION, desc);
            putValue(LARGE_ICON_KEY, thumb);
        }
        @Override
        public void actionPerformed(ActionEvent e) {
            image.setIcon(displayPhoto);
            setTitle(Main.blogname+": " + getValue(SHORT_DESCRIPTION).toString());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Gui gui = new Gui();
                gui.setVisible(true);
                gui.hiresbutton.setEnabled(false);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField blogname;
    private javax.swing.JTextField end;
    private javax.swing.JButton hiresbutton;
    private javax.swing.JLabel httplabel;
    private javax.swing.JLabel image;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton resetbutton;
    private javax.swing.JButton runbutton;
    private javax.swing.JTextField start;
    private javax.swing.JToolBar thumbbar;
    private javax.swing.JLabel tolabel;
    private javax.swing.JLabel tumblrlabel;
    // End of variables declaration//GEN-END:variables
}
